version: '3.8'

services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
    - 3306:3306
    expose:
      - 3306

  backend:
    build:
      context: ./backend
    command: >
        sh -c "npx prisma generate && npx prisma migrate dev --name init && npm start"
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:example@mysql:3306/mydatabase
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
