# Use the official Node.js image as a base
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) into the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files into the container
COPY . .

#Generate Prisma client
RUN npx prisma generate

# Expose the port that the backend app will run on
EXPOSE 5000

# Start the backend server
CMD ["npm", "start"]